version: '3'


services:
  ml_service:
    container_name: ml_service
    build: ml_service
    volumes:
      - ./ml_service:/app
    ports:
      - "8001:8001"
    networks:
      - ml_network
    env_file:
      - app_ml.env


  registry_service:
    container_name: registry_service
    build: registry_service
    volumes:
      - ./registry_service:/app
    ports:
      - "8002:8002"
    networks:
      - registry_network
    env_file:
      - app_registry.env


  nginx:
    container_name: fastapi_reverse_proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ml_service
    networks:
      - default
      - ml_network
      - registry_network

networks:
  default:
    external:
      name:
        microservice_network

  ml_network:
    external:
      name: ml_network

  registry_network:
    external:
      name: registry_network

